services:
  api:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    command: ["bun", "run", "dev"] 
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
      target: development 
    ports:
      - "3000:3000" 
    volumes:
      - ./frontend:/app
      - /app/node_modules


  nginx:
    ports:
      - "80:3000" 

  db:
    ports:
      - "5432:5432"