CREATE TABLE IF NOT EXISTS recipes (
    id UUID PRIMARY KEY,
    recipe_name VARCHAR(256) NOT NULL,
    ingredients TEXT[] NOT NULL,
    instructions TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);